# NumPy

In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [7]:
pip list

Package                       VersionNote: you may need to restart the kernel to use updated packages.

----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.wea

In [5]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.14.0               |   py39haa95532_0         937 KB
    ------------------------------------------------------------
                                           Total:         937 KB

The following packages will be UPDATED:

  conda                               4.12.0-py39haa95532_0 --> 4.14.0-py39haa95532_0




conda-4.14.0         | 937 KB    |            |   0% 
conda-4.14.0         | 937 KB    | 1          |   2% 
conda-4.14.0         | 937 KB    | 8          |   9% 
conda-4.14.0         | 937 KB    | ##         |  20% 
conda-4.14.0         | 937 KB    | ####4      |  44% 
conda-4.14.0         | 937 KB    | ########7  |  87% 
conda-4.14.0         | 937 KB    | ########## | 100% 
P


EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\Anaconda3




In [10]:
import numpy as np

In [11]:
print(np.__version__)

1.21.5


In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
print(type(arr))

<class 'numpy.ndarray'>


In [32]:
print(np.amin(arr))
print(np.amax(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.ptp(arr))
print(np.std(arr))
print(np.var(arr))
print(np.average(arr))
print(np.percentile(arr,10))

1
10
5.5
5.5
9
2.8722813232690143
8.25
5.5
1.9


In [34]:
arr = np.array([[1,2,3],[4,5,6],[1,2,3]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [37]:
#create simple array from the list

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
#dimension of the array

print(arr.ndim)

2


In [39]:
#shape of the array

print(arr.shape)

(2, 4)


In [40]:
#dimension of the array

print(type(arr))

<class 'numpy.ndarray'>


In [41]:
#dimension of the array

print(arr.data)

# Random Number Generator using numpy

In [47]:
from numpy import random
x= random.randint(100)
print(x)

8


In [62]:
from numpy import random
x= random.randint(10)
print(x)

8


In [64]:
from numpy import random
x= random.randint()
print(x)

TypeError: randint() takes at least 1 positional argument (0 given)

In [67]:
from numpy import random
x= random.randint(0)
print(x)

ValueError: high <= 0

In [69]:
from numpy import random
x= random.randint(1)
print(x)

0


In [70]:
#Generate Radndom Float

x = random.rand(10)
print(x)

[0.12366588 0.8305106  0.70252907 0.32266154 0.46389075 0.15241003
 0.87168406 0.80400578 0.76426344 0.75039277]


In [72]:
#Generate Radndom Float

x = random.randint(100, size=(5))
print(x)

[56 61 50 17 12]


In [75]:
from numpy import random
x= random.randint(100 ,size=(8))
print(x)

[53 26 40  8 39 63 86  5]


In [76]:
#Generate a 2D array with 3 rows , each row containing 5 random integer numbers

from numpy import random
x= random.randint(100 ,size=(3,5))
print(x)

[[26 58 43 85 21]
 [46 28 19  0 41]
 [88 69 94 37 56]]


In [81]:
#Generate a 2D array with 3 rows , each row containing 5 random integer numbers

from numpy import random
random.seed(101)
x= random.randint(100 ,size=(3,5))
print(x)

[[95 11 81 70 63]
 [87 75  9 77 40]
 [ 4 63 40 60 92]]


# 2.4 PRACTICAL : Creating scalars in numpy


In [83]:
#import numpy

import numpy as np

#creating 1-D list
list1 = [1,2,3]

#creating 1-D list vertical

list2 = [[10],
         [20],
         [30]]

#create vector1

vector1 = np.array(list1)
vector2 = np.array(list2)

print("Horizantal Vector")
print(vector1)

print("------------------")

print("Vertical Vector")
print(vector2)



Horizantal Vector
[1 2 3]
------------------
Vertical Vector
[[10]
 [20]
 [30]]


# 2.6 PRACTICAL Creating Matrix in Numpy

In [84]:
import numpy as np

a=np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [85]:
import numpy as np

a=np.matrix('1 2; 3 4')
print("Via string input : \n", a, "\n\n")



Via string input : 
 [[1 2]
 [3 4]] 




In [101]:
import numpy as np

a=np.matrix('1 2; 3 4')
print("Via string input : \n", a, "\n\n")

#array-like input
b = np.matrix([[5,6,7], [4,6],])
print("Via array-line input :\n", b)

Via string input : 
 [[1 2]
 [3 4]] 


Via array-line input :
 [[list([5, 6, 7]) list([4, 6])]]


# 2.7  PRACTICAL : Matrix Multiplication in Numpy

In [105]:
import numpy as np

A = 5

B = [[6, 7],
     [8, 9]]

print(np.dot(A,B))

[[30 35]
 [40 45]]


In [111]:
import numpy as np

A = [[6, 7],
     [8, 9]]

B = [[1, 3],
     [5, 7]]

print(np.dot(A,B))

print("---------Hardik----------")

print(np.dot(B,A))

[[41 67]
 [53 87]]
---------Hardik----------
[[30 34]
 [86 98]]


In [114]:
A = ([1,2,3],[4,5,6],[7,8,9])

np.transpose(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# 2.8 PRACTICAL : Measure of central Tendency Using Numpy

In [2]:
import numpy as np
data = [32, 36, 46, 47, 56, 69, 75, 79, 79, 88, 89, 91, 92, 93, 96, 97, 98, 99, 100, 101 ]

#First quartile(Q1)

Q1 = np.median(data[:10])
Q1

62.5

In [4]:
import numpy as np
data = [32, 36, 46, 47, 56, 69, 75, 79, 79, 88, 89, 91, 92, 93, 96, 97, 98, 99, 100, 101 ]

#tHIRD quartile(Q3)

Q3 = np.median(data[10:])
Q3

96.5

In [8]:
#interquartile range

IQR = Q3 - Q1

print(IQR)

34.0


In [12]:
import numpy as np
data = [32, 36, 46, 47, 56, 69, 75, 79, 79, 88, 89, 91, 92, 93, 96, 97, 98, 99, 100, 101 ]
Q1 = np.median(data[:10])
print(Q1)

Q2 = np.median(data[10:])
print(Q2)

IQR = Q2 - Q1

print(IQR)

62.5
96.5
34.0


# 2.10 practical : Array Broadcasting in numpy

In [13]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

a*b

array([2., 4., 6.])

In [14]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0

a*b

array([2., 4., 6.])

# Calculate BMI of cricket players

In [5]:
#Heights of players

import numpy as np

hg_in = [61, 65, 64, 69, 70, 68, 64, 63, 62, 66, 72]

#convert into numpy array

ht_np = np.array(hg_in)

#convert height from inch into meter by exposing it to 0.0245
ht_np = ht_np * 0.0245

ht_np

array([1.4945, 1.5925, 1.568 , 1.6905, 1.715 , 1.666 , 1.568 , 1.5435,
       1.519 , 1.617 , 1.764 ])

In [6]:
#weight of players in pound

wt_pd = [100,200,160,180,140,155,165,172,180,200,168]

#convert into array
wt_np = np.array(wt_pd)

#convert height from pound to kg by exposing it to 0.45
wt_np = wt_np * 0.45

wt_np

array([45.  , 90.  , 72.  , 81.  , 63.  , 69.75, 74.25, 77.4 , 81.  ,
       90.  , 75.6 ])

In [7]:
#BMI calculation

BMI = wt_np/(ht_np ** 2)
BMI

array([20.1474773 , 35.48817184, 29.28467305, 28.3435777 , 21.41964658,
       25.13010006, 30.19981909, 32.48835283, 35.10503991, 34.42091966,
       24.29543246])

In [10]:
BMI[-1]

24.295432458697764

In [11]:
BMI[BMI<21]

array([20.1474773])

In [12]:
BMI[:5]

array([20.1474773 , 35.48817184, 29.28467305, 28.3435777 , 21.41964658])

In [13]:
players = np.array([wt_np,ht_np])
players

array([[45.    , 90.    , 72.    , 81.    , 63.    , 69.75  , 74.25  ,
        77.4   , 81.    , 90.    , 75.6   ],
       [ 1.4945,  1.5925,  1.568 ,  1.6905,  1.715 ,  1.666 ,  1.568 ,
         1.5435,  1.519 ,  1.617 ,  1.764 ]])

In [14]:
players[0][2]

72.0

In [16]:
players[1][2]

1.568

In [17]:
players[1]

array([1.4945, 1.5925, 1.568 , 1.6905, 1.715 , 1.666 , 1.568 , 1.5435,
       1.519 , 1.617 , 1.764 ])

In [21]:
#Transpose

pT = players.transpose()
pT

array([[45.    ,  1.4945],
       [90.    ,  1.5925],
       [72.    ,  1.568 ],
       [81.    ,  1.6905],
       [63.    ,  1.715 ],
       [69.75  ,  1.666 ],
       [74.25  ,  1.568 ],
       [77.4   ,  1.5435],
       [81.    ,  1.519 ],
       [90.    ,  1.617 ],
       [75.6   ,  1.764 ]])

In [22]:
pT.shape

(11, 2)

In [28]:
#sranstical and mathematical function on players data

print(np.mean(wt_np))

print(np.median(wt_np))

print(np.sum(wt_np))

#standard daviation
print(np.std(wt_np))

#standard daviation
print(np.corrcoef(wt_np,ht_np))

74.45454545454545
75.60000000000001
819.0
12.082941667443528
[[1.         0.16451886]
 [0.16451886 1.        ]]
